# Generated by Django 2.0.7 on 2018-10-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app17', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='no',
            new_name='_id',
        ),
    ]
