# Generated by Django 2.0.7 on 2018-10-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('idno', models.IntegerField(default=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('duration', models.IntegerField(default=3)),
                ('fee', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('idno', models.IntegerField(default=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField(default=10)),
                ('exp', models.DecimalField(decimal_places=1, max_digits=4)),
                ('course', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewClass',
            fields=[
                ('cid', models.IntegerField(default=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('faculty_name', models.CharField(max_length=50)),
            ],
        ),
    ]
